In [2]:
import pandas as pd 
import numpy as np

In [149]:
pd.__version__

'2.3.3'

In [3]:
#Task 1:Creating three dataframes employee,seniority,project) 
There are three different tables as given above. Please make three dataframe in python 
and save them as three .csv files. From Task 2 to Task 10, use the saved .csv files only.

SyntaxError: invalid syntax (4005464764.py, line 2)

In [4]:
# Creating Project DataFrame
project_df = pd.DataFrame({
    "ID": ["A001","A002","A003","A004","A005","A002","A005","A003","A001","A003","A001","A004","A004","A005"],
    "Project": ["Project 1","Project 2","Project 3","Project 4","Project 5","Project 6","Project 7","Project 8","Project 9","Project 10","Project 11","Project 12","Project 13","Project 14"],
    "Cost": [1002000,2000000,4500000,5500000,None,680000,400000,350000,None,300000,2000000,1000000,3000000,200000],
    "Status": ["Finished","Ongoing","Finished","Ongoing","Finished","Failed","Finished","Failed","Ongoing","Finished","Failed","Ongoing","Finished","Finished"]
})

project_df

      ID     Project       Cost    Status
0   A001   Project 1  1002000.0  Finished
1   A002   Project 2  2000000.0   Ongoing
2   A003   Project 3  4500000.0  Finished
3   A004   Project 4  5500000.0   Ongoing
4   A005   Project 5        NaN  Finished
5   A002   Project 6   680000.0    Failed
6   A005   Project 7   400000.0  Finished
7   A003   Project 8   350000.0    Failed
8   A001   Project 9        NaN   Ongoing
9   A003  Project 10   300000.0  Finished
10  A001  Project 11  2000000.0    Failed
11  A004  Project 12  1000000.0   Ongoing
12  A004  Project 13  3000000.0  Finished
13  A005  Project 14   200000.0  Finished

In [5]:
# Creating Employee DataFrame
employee_df = pd.DataFrame({
    "ID": ["A001","A002","A003","A004","A005"],
    "Name": ["John Alter","Alice Luxemburg","Tom Sabestine","Nina Adgra","Amy Johny"],
    "Gender": ["M","F","M","F","F"],
    "City": ["Paris","London","Berlin","Newyork","Madrid"],
    "Age": [25,27,29,31,30]
})

employee_df

     ID             Name Gender     City  Age
0  A001       John Alter      M    Paris   25
1  A002  Alice Luxemburg      F   London   27
2  A003    Tom Sabestine      M   Berlin   29
3  A004       Nina Adgra      F  Newyork   31
4  A005        Amy Johny      F   Madrid   30

In [7]:
# Creating Seniority DataFrame
seniority_df = pd.DataFrame({
    "ID": ["A001","A002","A003","A004","A005"],
    "Designation Level": [2,2,3,2,3]
})

seniority_df

     ID  Designation Level
0  A001                  2
1  A002                  2
2  A003                  3
3  A004                  2
4  A005                  3

In [8]:
project_df.to_csv("project.csv", index=False)
employee_df.to_csv("employee.csv", index=False)
seniority_df.to_csv("seniority.csv", index=False)

In [ ]:
#Task 2 : FILLING MISSING VALUE IN COST COLUMN USING RUNNING AVERAGE #USE PF LOOP AS REQUIRED 
The cost column in the dataframe “Project” has some missing values. Your task is to 
compute these missing values. Replace the missing values by running average. You 
should use the “For” loop for this task.

In [158]:

pd.options.display.float_format = '{:.0f}'.format

# Fill missing Cost using running average

running_sum = 0
count = 0

for i in range(len(project_df)):
    
    # If value is NOT missing
    if pd.notna(project_df.loc[i, "Cost"]):
        running_sum += project_df.loc[i, "Cost"]
        count += 1
    
    # If value is missing
    else:
        project_df.loc[i, "Cost"] = running_sum / count

# Show updated dataframe
project_df

      ID     Project    Cost    Status
0   A001   Project 1 1002000  Finished
1   A002   Project 2 2000000   Ongoing
2   A003   Project 3 4500000  Finished
3   A004   Project 4 5500000   Ongoing
4   A005   Project 5 3250500  Finished
5   A002   Project 6  680000    Failed
6   A005   Project 7  400000  Finished
7   A003   Project 8  350000    Failed
8   A001   Project 9 2061714   Ongoing
9   A003  Project 10  300000  Finished
10  A001  Project 11 2000000    Failed
11  A004  Project 12 1000000   Ongoing
12  A004  Project 13 3000000  Finished
13  A005  Project 14  200000  Finished

In [ ]:
#Task 3 : Split name column into First Name and last Name #Removing original name column 
Split the name column in the Employee dataframe into two new columns “First Name”, 
and “Last Name” and remove the older “name” column.

In [159]:
employee_df

     ID             Name Gender     City  Age
0  A001       John Alter      M    Paris   25
1  A002  Alice Luxemburg      F   London   27
2  A003    Tom Sabestine      M   Berlin   29
3  A004       Nina Adgra      F  Newyork   31
4  A005        Amy Johny      F   Madrid   30

In [160]:
# print(employee_df["Name"].str.split(" ").str[0])

employee_df["First Name"] = employee_df["Name"].str.split(" ").str[0] # spiltted the Name column based on space (" ") and created a new column - First Name

In [161]:
# print(employee_df["Name"].str.split(" ").str[1])

employee_df["Last Name"] = employee_df["Name"].str.split(" ").str[1] # spiltted the Name column based on space (" ") and created a new column - Last Name

In [162]:
employee_df

     ID             Name Gender     City  Age First Name  Last Name
0  A001       John Alter      M    Paris   25       John      Alter
1  A002  Alice Luxemburg      F   London   27      Alice  Luxemburg
2  A003    Tom Sabestine      M   Berlin   29        Tom  Sabestine
3  A004       Nina Adgra      F  Newyork   31       Nina      Adgra
4  A005        Amy Johny      F   Madrid   30        Amy      Johny

In [163]:
#new drop name column,
employee_df.drop("Name",axis=1,inplace = True)

In [164]:
employee_df

     ID Gender     City  Age First Name  Last Name
0  A001      M    Paris   25       John      Alter
1  A002      F   London   27      Alice  Luxemburg
2  A003      M   Berlin   29        Tom  Sabestine
3  A004      F  Newyork   31       Nina      Adgra
4  A005      F   Madrid   30        Amy      Johny

In [ ]:
#Task_4: Join all three dataframes in one single dataframe. Name it “Final”

In [165]:
merge_1 = pd.merge(project_df,employee_df,left_on="ID",right_on="ID",how="inner")

In [166]:
Final_df = pd.merge(merge_1,seniority_df,on="ID",how="inner")
Final_df

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name,Designation Level
0,A001,Project 1,1002000,Finished,M,Paris,25,John,Alter,2
1,A002,Project 2,2000000,Ongoing,F,London,27,Alice,Luxemburg,2
2,A003,Project 3,4500000,Finished,M,Berlin,29,Tom,Sabestine,3
3,A004,Project 4,5500000,Ongoing,F,Newyork,31,Nina,Adgra,2
4,A005,Project 5,3250500,Finished,F,Madrid,30,Amy,Johny,3
5,A002,Project 6,680000,Failed,F,London,27,Alice,Luxemburg,2
6,A005,Project 7,400000,Finished,F,Madrid,30,Amy,Johny,3
7,A003,Project 8,350000,Failed,M,Berlin,29,Tom,Sabestine,3
8,A001,Project 9,2061714,Ongoing,M,Paris,25,John,Alter,2
9,A003,Project 10,300000,Finished,M,Berlin,29,Tom,Sabestine,3
10,A001,Project 11,2000000,Failed,M,Paris,25,John,Alter,2
11,A004,Project 12,1000000,Ongoing,F,Newyork,31,Nina,Adgra,2
12,A004,Project 13,3000000,Finished,F,Newyork,31,Nina,Adgra,2
13,A005,Project 14,200000,Finished,F,Madrid,30,Amy,Johny,3

In [ ]:
#ask_5: Add a new bonus column in the Final dataframe. Give a 5% bonus concerning project cost only to employees who have finished the projects.

In [167]:
Final_df["Bonus"]= np.where(Final_df["Status"]=="Finished", Final_df["Cost"]*0.05,0)
Final_df

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name,Designation Level,Bonus
0,A001,Project 1,1002000,Finished,M,Paris,25,John,Alter,2,50100
1,A002,Project 2,2000000,Ongoing,F,London,27,Alice,Luxemburg,2,0
2,A003,Project 3,4500000,Finished,M,Berlin,29,Tom,Sabestine,3,225000
3,A004,Project 4,5500000,Ongoing,F,Newyork,31,Nina,Adgra,2,0
4,A005,Project 5,3250500,Finished,F,Madrid,30,Amy,Johny,3,162525
5,A002,Project 6,680000,Failed,F,London,27,Alice,Luxemburg,2,0
6,A005,Project 7,400000,Finished,F,Madrid,30,Amy,Johny,3,20000
7,A003,Project 8,350000,Failed,M,Berlin,29,Tom,Sabestine,3,0
8,A001,Project 9,2061714,Ongoing,M,Paris,25,John,Alter,2,0
9,A003,Project 10,300000,Finished,M,Berlin,29,Tom,Sabestine,3,15000
10,A001,Project 11,2000000,Failed,M,Paris,25,John,Alter,2,0
11,A004,Project 12,1000000,Ongoing,F,Newyork,31,Nina,Adgra,2,0
12,A004,Project 13,3000000,Finished,F,Newyork,31,Nina,Adgra,2,150000
13,A005,Project 14,200000,Finished,F,Madrid,30,Amy,Johny,3,10000

In [168]:
Final_df[Final_df["Bonus"] != 0.0]

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name,Designation Level,Bonus
0,A001,Project 1,1002000,Finished,M,Paris,25,John,Alter,2,50100
2,A003,Project 3,4500000,Finished,M,Berlin,29,Tom,Sabestine,3,225000
4,A005,Project 5,3250500,Finished,F,Madrid,30,Amy,Johny,3,162525
6,A005,Project 7,400000,Finished,F,Madrid,30,Amy,Johny,3,20000
9,A003,Project 10,300000,Finished,M,Berlin,29,Tom,Sabestine,3,15000
12,A004,Project 13,3000000,Finished,F,Newyork,31,Nina,Adgra,2,150000
13,A005,Project 14,200000,Finished,F,Madrid,30,Amy,Johny,3,10000

In [169]:
Final_df[Final_df["Bonus"] == 0.0]

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name,Designation Level,Bonus
1,A002,Project 2,2000000,Ongoing,F,London,27,Alice,Luxemburg,2,0
3,A004,Project 4,5500000,Ongoing,F,Newyork,31,Nina,Adgra,2,0
5,A002,Project 6,680000,Failed,F,London,27,Alice,Luxemburg,2,0
7,A003,Project 8,350000,Failed,M,Berlin,29,Tom,Sabestine,3,0
8,A001,Project 9,2061714,Ongoing,M,Paris,25,John,Alter,2,0
10,A001,Project 11,2000000,Failed,M,Paris,25,John,Alter,2,0
11,A004,Project 12,1000000,Ongoing,F,Newyork,31,Nina,Adgra,2,0

In [ ]:
#Task 6 
Demote the designation level by 1, whose projects have status “fail”. Delete the 
employees record whose designation level is above 4.

In [10]:
final_df = pd.merge(project_df, employee_df, on="ID")
final_df = pd.merge(final_df, seniority_df, on="ID")

In [12]:
final_df.rename(columns={"Designation Level": "Designation"}, inplace=True)

In [13]:
# Demote for failed projects
final_df.loc[final_df["Status"] == "Failed", "Designation"] += 1

# Remove designation > 4
final_df = final_df[final_df["Designation"] <= 4]

# Show result
final_df

,ID,Project,Cost,Status,Name,Gender,City,Age,Designation
0,A001,Project 1,1002000.0,Finished,John Alter,M,Paris,25,2
1,A002,Project 2,2000000.0,Ongoing,Alice Luxemburg,F,London,27,2
2,A003,Project 3,4500000.0,Finished,Tom Sabestine,M,Berlin,29,3
3,A004,Project 4,5500000.0,Ongoing,Nina Adgra,F,Newyork,31,2
4,A005,Project 5,NaN,Finished,Amy Johny,F,Madrid,30,3
5,A002,Project 6,680000.0,Failed,Alice Luxemburg,F,London,27,3
6,A005,Project 7,400000.0,Finished,Amy Johny,F,Madrid,30,3
7,A003,Project 8,350000.0,Failed,Tom Sabestine,M,Berlin,29,4
8,A001,Project 9,NaN,Ongoing,John Alter,M,Paris,25,2
9,A003,Project 10,300000.0,Finished,Tom Sabestine,M,Berlin,29,3
10,A001,Project 11,2000000.0,Failed,John Alter,M,Paris,25,3
11,A004,Project 12,1000000.0,Ongoing,Nina Adgra,F,Newyork,31,2
12,A004,Project 13,3000000.0,Finished,Nina Adgra,F,Newyork,31,2
13,A005,Project 14,200000.0,Finished,Amy Johny,F,Madrid,30,3

In [14]:
final_df["Bonus"] = np.where(final_df["Status"] == "Finished",
                            final_df["Cost"] * 0.05,
                            0)

final_df

,ID,Project,Cost,Status,Name,Gender,City,Age,Designation,Bonus
0,A001,Project 1,1002000.0,Finished,John Alter,M,Paris,25,2,50100.0
1,A002,Project 2,2000000.0,Ongoing,Alice Luxemburg,F,London,27,2,0.0
2,A003,Project 3,4500000.0,Finished,Tom Sabestine,M,Berlin,29,3,225000.0
3,A004,Project 4,5500000.0,Ongoing,Nina Adgra,F,Newyork,31,2,0.0
4,A005,Project 5,NaN,Finished,Amy Johny,F,Madrid,30,3,NaN
5,A002,Project 6,680000.0,Failed,Alice Luxemburg,F,London,27,3,0.0
6,A005,Project 7,400000.0,Finished,Amy Johny,F,Madrid,30,3,20000.0
7,A003,Project 8,350000.0,Failed,Tom Sabestine,M,Berlin,29,4,0.0
8,A001,Project 9,NaN,Ongoing,John Alter,M,Paris,25,2,0.0
9,A003,Project 10,300000.0,Finished,Tom Sabestine,M,Berlin,29,3,15000.0
10,A001,Project 11,2000000.0,Failed,John Alter,M,Paris,25,3,0.0
11,A004,Project 12,1000000.0,Ongoing,Nina Adgra,F,Newyork,31,2,0.0
12,A004,Project 13,3000000.0,Finished,Nina Adgra,F,Newyork,31,2,150000.0
13,A005,Project 14,200000.0,Finished,Amy Johny,F,Madrid,30,3,10000.0

In [ ]:
#Task_7: Add “Mr.” and “Mrs.” to the first name column and #removing gender column

In [174]:

                                 "Mrs. " + final_df["First Name"])

# Drop Gender column
final_df.drop("Gender", axis=1, inplace=True)

# Show result
final_df

,ID,Project,Cost,Status,City,Age,First Name,Last Name,Designation,Bonus
0,A001,Project 1,1002000,Finished,Paris,25,Mr. John,Alter,2,50100
1,A002,Project 2,2000000,Ongoing,London,27,Mrs. Alice,Luxemburg,2,0
2,A003,Project 3,4500000,Finished,Berlin,29,Mr. Tom,Sabestine,3,225000
3,A004,Project 4,5500000,Ongoing,Newyork,31,Mrs. Nina,Adgra,2,0
4,A005,Project 5,3250500,Finished,Madrid,30,Mrs. Amy,Johny,3,162525
5,A002,Project 6,680000,Failed,London,27,Mrs. Alice,Luxemburg,1,0
6,A005,Project 7,400000,Finished,Madrid,30,Mrs. Amy,Johny,3,20000
7,A003,Project 8,350000,Failed,Berlin,29,Mr. Tom,Sabestine,2,0
8,A001,Project 9,2061714,Ongoing,Paris,25,Mr. John,Alter,2,0
9,A003,Project 10,300000,Finished,Berlin,29,Mr. Tom,Sabestine,3,15000
10,A001,Project 11,2000000,Failed,Paris,25,Mr. John,Alter,1,0
11,A004,Project 12,1000000,Ongoing,Newyork,31,Mrs. Nina,Adgra,2,0
12,A004,Project 13,3000000,Finished,Newyork,31,Mrs. Nina,Adgra,2,150000
13,A005,Project 14,200000,Finished,Madrid,30,Mrs. Amy,Johny,3,10000

In [ ]:
Task 8 
Promote designation level by 1 for the employees whose age is more than 29 years #using if condition 
IF condition.

In [15]:
 #Promote employees with age > 29
final_df.loc[final_df["Age"] > 29, "Designation"] -= 1

# Show result
final_df

,ID,Project,Cost,Status,Name,Gender,City,Age,Designation,Bonus
0,A001,Project 1,1002000.0,Finished,John Alter,M,Paris,25,2,50100.0
1,A002,Project 2,2000000.0,Ongoing,Alice Luxemburg,F,London,27,2,0.0
2,A003,Project 3,4500000.0,Finished,Tom Sabestine,M,Berlin,29,3,225000.0
3,A004,Project 4,5500000.0,Ongoing,Nina Adgra,F,Newyork,31,1,0.0
4,A005,Project 5,NaN,Finished,Amy Johny,F,Madrid,30,2,NaN
5,A002,Project 6,680000.0,Failed,Alice Luxemburg,F,London,27,3,0.0
6,A005,Project 7,400000.0,Finished,Amy Johny,F,Madrid,30,2,20000.0
7,A003,Project 8,350000.0,Failed,Tom Sabestine,M,Berlin,29,4,0.0
8,A001,Project 9,NaN,Ongoing,John Alter,M,Paris,25,2,0.0
9,A003,Project 10,300000.0,Finished,Tom Sabestine,M,Berlin,29,3,15000.0
10,A001,Project 11,2000000.0,Failed,John Alter,M,Paris,25,3,0.0
11,A004,Project 12,1000000.0,Ongoing,Nina Adgra,F,Newyork,31,1,0.0
12,A004,Project 13,3000000.0,Finished,Nina Adgra,F,Newyork,31,1,150000.0
13,A005,Project 14,200000.0,Finished,Amy Johny,F,Madrid,30,2,10000.0

In [ ]:
Task 9 
Add the cost of all projects for each Employee and save it in new dataframe 
“TotalProjCost” with three columns ID, First Name, and Total cost # calculating total project cost for each  employee

In [176]:
# Group by ID and First Name, then sum cost
TotalProjCost = final_df.groupby(["ID", "First Name"])["Cost"].sum().reset_index()

# Rename column
TotalProjCost.rename(columns={"Cost": "Total Cost"}, inplace=True)

# Show result
TotalProjCost

     ID  First Name  Total Cost
0  A001    Mr. John     5063714
1  A002  Mrs. Alice     2680000
2  A003     Mr. Tom     5150000
3  A004   Mrs. Nina     9500000
4  A005    Mrs. Amy     3850500

In [177]:
TotalProjCost.to_csv("TotalProjectCost.csv",index=False)

In [ ]:
Task 10 
Print all the employee details whose city name contains the letter “o” in it.

In [178]:
# Filter cities containing "o"
result = final_df[final_df["City"].str.contains("o", case=False)]

# Show result
result

,ID,Project,Cost,Status,City,Age,First Name,Last Name,Designation,Bonus
1,A002,Project 2,2000000,Ongoing,London,27,Mrs. Alice,Luxemburg,2,0
3,A004,Project 4,5500000,Ongoing,Newyork,31,Mrs. Nina,Adgra,3,0
5,A002,Project 6,680000,Failed,London,27,Mrs. Alice,Luxemburg,1,0
11,A004,Project 12,1000000,Ongoing,Newyork,31,Mrs. Nina,Adgra,3,0
12,A004,Project 13,3000000,Finished,Newyork,31,Mrs. Nina,Adgra,3,150000

In [179]:
cities = final_df["City"].to_list() # converting series to list
cities

['Paris',
 'London',
 'Berlin',
 'Newyork',
 'Madrid',
 'London',
 'Madrid',
 'Berlin',
 'Paris',
 'Berlin',
 'Paris',
 'Newyork',
 'Newyork',
 'Madrid']